version: '3.3'
services:
  #Demo Devops Python
  demo-devops-python.tembare.com:
    build: .
    container_name: demo-devops-python.tembare.com
    restart: unless-stopped
    tty: true
    ports:
     - "6000:7200"
    command: python3 -m flask run --host=0.0.0.0 --port=7200
networks:
  default:
    external:
        name: tembare-container-network

